config/routes.rb
TimesheetConverter::Application.routes.draw do

  resources :tgl_rows

  root to: 'static_pages#home'

  get "static_pages/home"

  get "converters/weekly"

  get "converters/daily"

  post "converters/upload_tgl_daily_csv"

  get "converters/view"

end

app/models/tgl_row.rb
class TglRow < ActiveRecord::Base
  attr_accessible :billable, :client, :description, :email, :end_date, :start_date, :tags, :task, :usd_amount, :user_name

  def activity_duration
      return ((self.end_date - self.start_date) / 3600.0).round(2)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/converters_controller.rb
class ConvertersController < ApplicationController
  def weekly
  end

  def daily
  end

  def upload_tgl_daily_csv
    require 'fileutils'
    require 'csv'

    # need to find better way to instanciate dates
    csv_end_date = DateTime.parse('01.01.2015')
    csv_start_date = DateTime.parse('01.01.1999') # I would be be surprised if anyone would have problems with tis software in 2 years


    tmp = params[:upload][:file].tempfile

    file = File.join("public", params[:upload][:file].original_filename)

    FileUtils.cp tmp.path, file

    csv_text = File.read(file)
    csv = CSV.parse(csv_text, :headers => true)

    # add CSV records to DB without duplicates
    csv.each do |row|
        l = row.to_hash

        # get synthetic key
        start_date = DateTime.parse(l['Start date'] + ' ' + l['Start time'])
        end_date = DateTime.parse(l['End date'] + ' ' + l['End time'])

        # check if record exits
        db_rows = TglRow.where("start_date = :start_date AND end_date = :end_date",
                     {:start_date => start_date, :end_date => end_date })

        # destroy dulpicates
        if db_rows.any?
          db_rows.each do |r| r.destroy end
        end

        tgl_row = TglRow.new(billable: l['Billable'], client: l['Client'], description: l['Description'],
            email: l['Email'], end_date: end_date,
            start_date: start_date, tags: l['Tags'],
            task: l['Task'], usd_amount: l['Amount (USD)'], user_name: l['User'])

        if not tgl_row.save
          format.json { render json: tgl_row.errors, status: :unprocessable_entity }
        end

        csv_start_date = start_date if csv_start_date < start_date
        csv_end_date = end_date if csv_end_date > end_date
    end

    FileUtils.rm file
    redirect_to :action => 'view', :date_to_show_start => csv_start_date, :date_to_show_end => csv_end_date
    end


  def view

    @date_to_show_start = params[:date_to_show_start]
    @date_to_show_end = params[:date_to_show_end]

    @tgl_rows = TglRow.where("strftime('%s',start_date) <= strftime('%s',:start_date) AND strftime('%s',end_date) >= strftime('%s',:end_date)",
                         {:start_date => params[:date_to_show_start], :end_date => params[:date_to_show_end] })
    #metrics
    f = @tgl_rows.first
    @total_hours = 0.0
    @tgl_rows.each do |t| @total_hours = @total_hours + t.activity_duration end
    @total_hours = @total_hours.round(2)
    render
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
   def home

   end
end

app/controllers/tgl_rows_controller.rb
class TglRowsController < ApplicationController
  # GET /tgl_rows
  # GET /tgl_rows.json
  def index
    @tgl_rows = TglRow.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tgl_rows }
    end
  end

  # GET /tgl_rows/1
  # GET /tgl_rows/1.json
  def show
    @tgl_row = TglRow.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tgl_row }
    end
  end

  # GET /tgl_rows/new
  # GET /tgl_rows/new.json
  def new
    @tgl_row = TglRow.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tgl_row }
    end
  end

  # GET /tgl_rows/1/edit
  def edit
    @tgl_row = TglRow.find(params[:id])
  end

  # POST /tgl_rows
  # POST /tgl_rows.json
  def create
    @tgl_row = TglRow.new(params[:tgl_row])

    respond_to do |format|
      if @tgl_row.save
        format.html { redirect_to @tgl_row, notice: 'Tgl row was successfully created.' }
        format.json { render json: @tgl_row, status: :created, location: @tgl_row }
      else
        format.html { render action: "new" }
        format.json { render json: @tgl_row.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tgl_rows/1
  # PUT /tgl_rows/1.json
  def update
    @tgl_row = TglRow.find(params[:id])

    respond_to do |format|
      if @tgl_row.update_attributes(params[:tgl_row])
        format.html { redirect_to @tgl_row, notice: 'Tgl row was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tgl_row.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tgl_rows/1
  # DELETE /tgl_rows/1.json
  def destroy
    @tgl_row = TglRow.find(params[:id])
    @tgl_row.destroy

    respond_to do |format|
      format.html { redirect_to tgl_rows_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/converters_helper.rb
module ConvertersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tgl_rows_helper.rb
module TglRowsHelper
end

app/views/converters/daily.html.erb
<div class="center hero-unit">
  <h2>
    Upload you Tgl something and watch the miracle
  </h2>

    <h1>File Upload</h1>

    <%= form_tag({:action => 'upload_tgl_daily_csv'}, :multipart => true) %>

        <!-- {:controller => "api/#{CURRENT_API_VERSION}/api", :action => 'file', :method=> :post}, {:multipart => true}) -->
        <p><label for="upload_file">Select CSV File</label> :
        <%= file_field( "upload", "file" ) %></p>
        <%= submit_tag "Upload Tgl something" %>
</div>

app/views/converters/view.erb
<div class="center hero-unit">
  <h2>
    Upload you Tgl something and watch the miracle
  </h2>

  <h1>Total: <%= number_with_precision(@total_hours, :precision => 2) %> </h1>
  <table>
    <tr>
      <th>User name</th>
      <th>Email</th>
      <th>Client</th>
      <th>Task</th>
      <th>Description</th>
      <th>Billable</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Tags</th>
      <th>Usd amount</th>
    </tr>

  <% @tgl_rows.each do |tgl_row| %>
    <tr>
      <td><%= tgl_row.user_name %></td>
      <td><%= tgl_row.email %></td>
      <td><%= tgl_row.client %></td>
      <td><%= tgl_row.task %></td>
      <td><%= tgl_row.description %></td>
      <td><%= tgl_row.billable %></td>
      <td><%= tgl_row.start_date %></td>
      <td><%= tgl_row.end_date %></td>
      <td><%= tgl_row.tags %></td>
      <td><%= tgl_row.usd_amount %></td>
    </tr>
  <% end %>
  </table>
</div>

app/views/converters/weekly.html.erb
<h1>Converters#weekly</h1>
<p>Find me in app/views/converters/weekly.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "Timesheet converter", '#', id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Home",    '#' %></li>
            </ul>
          </nav>
        </div>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Welcome to the Jungle</h1>

  <h2>
    Missing tool for converting tgl time sheets to something meaningful
  </h2>

  <%= link_to "Tgl → P", { :controller => "converters", :action => "daily" }, { :class => "btn btn-large btn-primary" } %>
  <%= link_to "P → D", { :controller => "converters", :action => "weekly" }, { :class => "btn btn-large btn-primary"} %>

</div>

app/views/tgl_rows/_form.html.erb
<%= form_for(@tgl_row) do |f| %>
  <% if @tgl_row.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tgl_row.errors.count, "error") %> prohibited this tgl_row from being saved:</h2>

      <ul>
      <% @tgl_row.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_name %><br />
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :client %><br />
    <%= f.text_field :client %>
  </div>
  <div class="field">
    <%= f.label :task %><br />
    <%= f.text_field :task %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :billable %><br />
    <%= f.text_field :billable %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.datetime_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.datetime_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :tags %><br />
    <%= f.text_field :tags %>
  </div>
  <div class="field">
    <%= f.label :usd_amount %><br />
    <%= f.text_field :usd_amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tgl_rows/edit.html.erb
<h1>Editing tgl_row</h1>

<%= render 'form' %>

<%= link_to 'Show', @tgl_row %> |
<%= link_to 'Back', tgl_rows_path %>

app/views/tgl_rows/index.html.erb
<h1>Listing tgl_rows</h1>

<table>
  <tr>
    <th>User name</th>
    <th>Email</th>
    <th>Client</th>
    <th>Task</th>
    <th>Description</th>
    <th>Billable</th>
    <th>Start date</th>
    <th>End date</th>
    <th>Tags</th>
    <th>Usd amount</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tgl_rows.each do |tgl_row| %>
  <tr>
    <td><%= tgl_row.user_name %></td>
    <td><%= tgl_row.email %></td>
    <td><%= tgl_row.client %></td>
    <td><%= tgl_row.task %></td>
    <td><%= tgl_row.description %></td>
    <td><%= tgl_row.billable %></td>
    <td><%= tgl_row.start_date %></td>
    <td><%= tgl_row.end_date %></td>
    <td><%= tgl_row.tags %></td>
    <td><%= tgl_row.usd_amount %></td>
    <td><%= link_to 'Show', tgl_row %></td>
    <td><%= link_to 'Edit', edit_tgl_row_path(tgl_row) %></td>
    <td><%= link_to 'Destroy', tgl_row, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tgl row', new_tgl_row_path %>

app/views/tgl_rows/new.html.erb
<h1>New tgl_row</h1>

<%= render 'form' %>

<%= link_to 'Back', tgl_rows_path %>

app/views/tgl_rows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User name:</b>
  <%= @tgl_row.user_name %>
</p>

<p>
  <b>Email:</b>
  <%= @tgl_row.email %>
</p>

<p>
  <b>Client:</b>
  <%= @tgl_row.client %>
</p>

<p>
  <b>Task:</b>
  <%= @tgl_row.task %>
</p>

<p>
  <b>Description:</b>
  <%= @tgl_row.description %>
</p>

<p>
  <b>Billable:</b>
  <%= @tgl_row.billable %>
</p>

<p>
  <b>Start date:</b>
  <%= @tgl_row.start_date %>
</p>

<p>
  <b>End date:</b>
  <%= @tgl_row.end_date %>
</p>

<p>
  <b>Tags:</b>
  <%= @tgl_row.tags %>
</p>

<p>
  <b>Usd amount:</b>
  <%= @tgl_row.usd_amount %>
</p>


<%= link_to 'Edit', edit_tgl_row_path(@tgl_row) %> |
<%= link_to 'Back', tgl_rows_path %>